spring.application.name=employees-api
spring.datasource.url=jdbc:postgresql://localhost:5432/employees
spring.datasource.username=postgres
spring.datasource.password=kacper231
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=db/changelog/changelog-master.xml
spring.jpa.defer-datasource-initialization=false
spring.jpa.open-in-view=false
cors.allowed-origins=[http://localhost:4200, http://localhost:4200]
cors.allowed-methods=[DELETE, GET, POST, PUT]
cors.allowed-headers=Authorization
logging.level.org.springframework.security=DEBUG