#spring.application.name=employees-api
#spring.datasource.url=jdbc:postgresql://${AWS_RDS_DATABASE_HOST}:5432/${AWS_RDS_DATABASE}?useSSL=false\
#  &allowPublicKeyRetrieval=true&autoReconnect=true
#spring.datasource.username=${AWS_RDS_DATABASE_USERNAME}
#spring.datasource.password=${AWS_RDS_DATABASE_PASSWORD}

spring.datasource.url=jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=db/changelog/changelog-master.xml

spring.jpa.defer-datasource-initialization=false
spring.jpa.open-in-view=false